### ISSUE TITLE
5.4 causes issue in connexion

### ISSUE THREAD

**Issue by wang31** [yaml/pyyaml#479]
connexion includes PyYAML >= 5.1
After 5.4 release today, this error occurs. It was working fine with 5.3.1:
```
File "***/connexion/utils.py", line 4, in <module>
    import yaml
  File "***/yaml/__init__.py", line 13, in <module>
    from .cyaml import *
  File "***/yaml/cyaml.py", line 7, in <module>
    from _yaml import CParser, CEmitter
  File "***/site-packages/_yaml/__init__.py", line 8, in <module>
    if not yaml.__with_libyaml__:
AttributeError: partially initialized module 'yaml' has no attribute '__with_libyaml__' (most likely due to a circular import)
```

**Comment by wang31** [comment]
Duplicate of #478
