### ISSUE TITLE
Build on Python 3.8 fails

### ISSUE THREAD

**Issue by MeggyCal** [yaml/pyyaml#322]
When I build PyYAML with Python 3.8 I get following error (among tons of warnings):

[   12s] ext/_yaml.c:318:75: note: in definition of macro ‘__Pyx_PyCode_New’
[   12s]   318 |           PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
[   12s]       |                                                                           ^~~~~
[   12s] In file included from /usr/include/python3.8/compile.h:5,
[   12s]                  from /usr/include/python3.8/Python.h:138,
[   12s]                  from ext/_yaml.c:4:
[   12s] /usr/include/python3.8/code.h:122:28: note: expected ‘PyObject *’ {aka ‘struct _object *’} but argument is of type ‘int’
[   12s]   122 | PyAPI_FUNC(PyCodeObject *) PyCode_New(
[   12s]       |                            ^~~~~~~~~~
[   12s] ext/_yaml.c:318:11: error: too many arguments to function ‘PyCode_New’
[   12s]   318 |           PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
[   12s]       |           ^~~~~~~~~~

This Cython issue might solve similar problem: https://github.com/cython/cython/issues/2938

**Comment by nitzmahone** [comment]
This bug was fixed in pyyaml 5.1.1 on June 6 (a rebuild of the 5.1 sdist with the patched Cython)- you didn't say what version of the pyyaml dist you're building with, or if you built from the main sources yourself- if so, you'd need the updated Cython yourself. If you're building from PyPI or the official tarball, just make sure you're building with 5.1.1 (3.8 compat is the entire reason we released 5.1.1, and it's working fine everywhere we're using it with 3.8b2).

**Comment by nitzmahone** [comment]
Argh, nevermind- at a glance, looks like there may be a new header bug since 3.8.0b1

**Comment by nitzmahone** [comment]
@MeggyCal as a workaround, you can use PyYAML 5.1 for now, since the CPython folks decided to revert the original breaking change when 3.8.0b2 was released (which broke anyone that had already compensated for it). We'll release a 5.1.2 in the next couple days that's basically back to what 5.1 was- just waiting for 3.8.0b3 test containers to drop so we can verify there are no new breakages. Thanks for the report!

**Comment by MeggyCal** [comment]
thanks a lot!

**Comment by nitzmahone** [comment]
@MeggyCal 5.1.2 has been released- can you verify all's well with that, and close this if so?

**Comment by MeggyCal** [comment]
I have tested it, now it seems to work with 3.8.0b2. Thanks a lot!
