### ISSUE TITLE
PyYaml not working on Python 3.10

### ISSUE THREAD

**Issue by Wilhelmsson177** [yaml/pyyaml#574]
I created a new environment using poetry and added onyl pyyaml as a dependency.

Import of CLoader does not work.
```
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from yaml import CLoader
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'CLoader' from 'yaml' (C:\Users\Willi\AppData\Local\pypoetry\Cache\virtualenvs\pyyaml-310-mX9xe7OY-py3.10\lib\site-packages\yaml\__init__.py)
```

**Comment by nitzmahone** [comment]
Python 3.10 wheels are available only in 6.0 (currently in beta); try setting the dep to `pyyaml==6.0b1` to get it to install the prerelease. We're planning to ship those this week, barring any major showstoppers.
